# Generated by Django 3.2.5 on 2021-07-25 07:51

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210724_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, upload_to=restaurant.models.Meal.get_file_path),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
